---
name: release

on:
  workflow_run:
    workflows: [ci, lint]
    types: [completed]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Semantic Release
        run: |
          sudo npm install semantic-release -g
          sudo npm install @semantic-release/changelog -g
          sudo npm install @semantic-release/git -g
          sudo npm install @semantic-release/github -g
          sudo npm install @semantic-release/exec -g
          cargo install semantic-release-rust --version 1.0.0-alpha.8

      - name: Run Semantic Release
        run: semantic-release

        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
